### ISSUE TITLE
Requires R >= 3.5?

### ISSUE THREAD

**Issue by aarzalluz** [csoneson/jcc#1]
Hi,

I've tried to install the jcc package, but I'm having trouble due to the R>=3.5 requirement (I have R.3.4.4). I wasn't necessarily planning on updating R to version 3.5 yet, but I'm very interested in trying out your package. However, before I go ahead do so, I just wanted to make sure this is the only solution.

Thank you in advance,

Ángeles

**Comment by csoneson** [comment]
Hi, 
in general, I would recommend updating to R 3.5. However, if you want a quick workaround for R 3.4 you can always fork or clone the repository, change the DESCRIPTION file and install it from there. I can not guarantee that it will run smoothly though, I haven't tried it on R 3.4 and it may be that the behaviour or the API of some of its dependencies is different. 
Charlotte

**Comment by aarzalluz** [comment]
Thanks! I had an issue with vignette build using your workaround for 3.4.4, so ended up updating to R 3.5 instead of continuing. Turned out to be a much better idea in the end -like you said :)

Ángeles
