### ISSUE TITLE
Error regarding IRanges

### ISSUE THREAD

**Issue by nagzz** [csoneson/jcc#2]
Hi,
I am using the same transcriptome GTF file for jcc analysis with two different bam file. For one bam file, I could see the following lines but not for another one. Please check and let me know the possible reason to rectify the error.

```
Predicting junction coverages...
[1] "BGIOSGA015865-TA: In range 1: 'end' must be >= 'start' - 1.: .Call2(\"solve_user_SEW0\", start, end, width, PACKAGE = \"IRanges\")"
```
Thanks,
Nagesh

**Comment by csoneson** [comment]
Hard to say what's going wrong here without more info. Were both bam files aligned to the same reference?

**Comment by nagzz** [comment]
Used the same reference file for the alignment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by csoneson** [comment]
Can you check where this happens (e.g. using `traceback()`)? I guess it would be somewhere in this chunk: https://github.com/csoneson/jcc/blob/6a9cae24f8f8f858f151fa03471ef7d55f13b358/R/predictTxCoverage.R#L138-L152

**Comment by nagzz** [comment]
It shows no trace back available. Please check the output.
```
> predCovProfiles <- predictTxCoverage(biasModel = biasMod$biasModel, exonsByTx = biasMod$exonsByTx, bam = "../12_2_paired_2ndPass_Aligned.sortedByCoord.out.bam", tx2gene = tx2gene, genome = Oindica, genes = c("BGIOSGA.929","BGIOSGA.933"), nCores = 30, verbose = TRUE)
Predicting coverage for 2 transcripts...
BGIOSGA002101TA
BGIOSGA002100TA
[1] "BGIOSGA002100TA: In range 1: 'end' must be >= 'start' - 1.: .Call2(\"solve_user_SEW0\", start, end, width, PACKAGE = \"IRanges\")"
Predicting junction coverages...
[1] "BGIOSGA002101TA: In range 1: 'end' must be >= 'start' - 1.: .Call2(\"solve_user_SEW0\", start, end, width, PACKAGE = \"IRanges\")"
Predicting junction coverages...
> traceback()
No traceback available 
```

**Comment by csoneson** [comment]
Can you look at these transcripts in the GTF file to see if there is anything strange going on?

**Comment by nagzz** [comment]
I have used the same GTF file for another bam file and I haven't seen any of the errors. Please check the following gtf file of the transcripts
```
1	StringTie	transcript	7225271	7227331	1000	-	.	gene_id "BGIOSGA.933"; transcript_id "BGIOSGA002100TA"; ref_gene_id "BGIOSGA002100"; 
1	StringTie	exon	7225271	7225509	1000	-	.	gene_id "BGIOSGA.933"; transcript_id "BGIOSGA002100TA"; exon_id "1"; ref_gene_id "BGIOSGA002100"; 
1	StringTie	exon	7226716	7226940	1000	-	.	gene_id "BGIOSGA.933"; transcript_id "BGIOSGA002100TA"; exon_id "2"; ref_gene_id "BGIOSGA002100"; 
1	StringTie	exon	7227037	7227331	1000	-	.	gene_id "BGIOSGA.933"; transcript_id "BGIOSGA002100TA"; exon_id "3"; ref_gene_id "BGIOSGA002100"; 
1	StringTie	transcript	7211752	7215083	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; ref_gene_id "BGIOSGA002101"; 
1	StringTie	exon	7211752	7211966	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; exon_id "1"; ref_gene_id "BGIOSGA002101"; 
1	StringTie	exon	7213857	7214133	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; exon_id "2"; ref_gene_id "BGIOSGA002101"; 
1	StringTie	exon	7214222	7214367	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; exon_id "3"; ref_gene_id "BGIOSGA002101"; 
1	StringTie	exon	7214478	7214702	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; exon_id "4"; ref_gene_id "BGIOSGA002101"; 
1	StringTie	exon	7214807	7215083	1000	-	.	gene_id "BGIOSGA.929"; transcript_id "BGIOSGA002101TA"; exon_id "5"; ref_gene_id "BGIOSGA002101"; 
```

**Comment by csoneson** [comment]
Ok, I can't see anything directly weird there. I can't really say anything else based on only the error message - I suppose all the previous steps went through without significant warnings or errors? Since you have only two transcripts here, I would suggest to step through `predictTxCoverage()` line by line with your input files, and look at the output from each step to try to identify the problem.

**Comment by csoneson** [comment]
I'm closing this issue; feel free to reopen if the problem persists after following the suggestions above.
