### ISSUE TITLE
minSize and maxSize parameters in fitAlpinebiasmodel

### ISSUE THREAD

**Issue by nagzz** [csoneson/jcc#3]
Could you please let me know how to set the minSize and maxSize parameters. Initially I tried with default values and end up with error. But later tried with some random values and its working. I also tried with the longest read length as maxSize value and in some occasions, it's working fine.

Thanks,
Nagesh

**Comment by csoneson** [comment]
The default values (i.e., `NULL`) will estimate the values to use from the data (from the distribution of estimated fragment lengths). The parameters are passed onto `alpine::buildFragtypes()`, in which it is recommended that the interval between minsize and maxsize should contain the at least the central 95 percent of the fragment length distribution across samples.
